version: '3.8'
services:
  minio1:
    image: minio/minio
    volumes:
      - ./docker/minio/datas/data1:/datas/data1
      - ./docker/minio/datas/data2:/datas/data2
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...2}/data{1...4}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  minio2:
    image: minio/minio
    volumes:
      - ./docker/minio/datas/data3:/datas/data3
      - ./docker/minio/datas/data4:/datas/data4
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...2}/data{1...4}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  nginx-minio:
    image: nginx
    volumes:
      - ./docker/minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    depends_on:
      - minio1
      - minio2
  db:
    restart: always
    image: mysql
    tty: true
    command: --lower-case-table-names=1 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: scrapy_db
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/data:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  redis:
    restart: always
    image: redis
    container_name: redis
    command: redis-server --requirepass scrapy_redis
    ports:
      - 6379:6379
    networks:
      app_net:
        ipv4_address: 172.16.238.15
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/proxy:/etc/nginx/pixiv/
      - ./docker/proxy/ca:/etc/nginx/ca/
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      app_net:
        ipv4_address: 172.16.238.20

#  scrapy:
#    depends_on:
#      - db
#    tty: true
#    build:
#      context: ./docker
#      dockerfile: python
#    environment:
#      MYSQL_SERVICE: db
#      PROXY_PORT: 10809
#    volumes:
#      - ./space:/data/space
#      - ./runtime:/data/runtime
#      - .:/app
#      - ./docker/scrapy/ca-certificates:/usr/local/share/ca-certificates
#      - ./docker/scrapy/hosts:/etc/hosts
#    networks:
#      app_net:
#        ipv4_address: 172.16.238.25
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/25"