version: '3.8'
services:
  db:
    restart: always
    image: mysql
    tty: true
    command: --lower-case-table-names=1 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: scrapy_db
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/data:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  redis:
    restart: always
    image: redis
    container_name: redis
    command: redis-server --requirepass scrapy_redis
    ports:
      - 6379:6379
    networks:
      app_net:
        ipv4_address: 172.16.238.15
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/proxy:/etc/nginx/pixiv/
      - ./docker/proxy/ca:/etc/nginx/ca/
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      app_net:
        ipv4_address: 172.16.238.20
#  scrapy:
#    depends_on:
#      - db
#    tty: true
#    build:
#      context: ./docker
#      dockerfile: python
#    environment:
#      MYSQL_SERVICE: db
#      PROXY_PORT: 10809
#    volumes:
#      - ./space:/data/space
#      - ./runtime:/data/runtime
#      - .:/app
#      - ./docker/scrapy/ca-certificates:/usr/local/share/ca-certificates
#      - ./docker/scrapy/hosts:/etc/hosts
#    networks:
#      app_net:
#        ipv4_address: 172.16.238.25
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/25"